---
- name: PLAY gestion infra
  hosts: local

  tasks:

    - name: Add Management Network VM Portgroup to Cluster
      vmware_portgroup:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        cluster_name: Cluster
        switch: vSwitch0
        portgroup: VLAN-Loubna
        vlan_id: 1000
        validate_certs: no
        state: present 
      delegate_to: localhost

    - name: Create a tag loubna
      vmware_tag:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        validate_certs: no
        category_id: 'urn:vmomi:InventoryServiceCategory:ae1957ef-839b-468c-ac6a-df722535aeb1:GLOBAL'
        tag_name: loubna
        tag_description: Tag loubna dans la catégorie Proprio
        state: present
      delegate_to: localhost


#    - name: Get category id from the given tag
#      vmware_tag_info:
#        hostname: vcsa.formation.lan
#        username: loubna
#        password: F0rmation!
#        validate_certs: no
#      register: tag_details
#    - debug:
#        msg: "{{ tag_details.tag_facts }}"

#Création de la vm loubna
    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        validate_certs: no
        name: Deb-loubna
        folder: /
        template: DebTemplate
        datacenter: Datacenter
      delegate_to: localhost

# Ajout de tag sur la machine loubna
    - name: Add tags to a virtual machine
      vmware_tag_manager:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        validate_certs: no
        tag_names:
          - loubna
        object_name: Deb-loubna
        object_type: VirtualMachine
        state: add
      delegate_to: localhost

## Modif de la date de création
    - name: Get timestamp from the system
      shell: "date +%d-%m-%Y%H-%M-%S"
      register: tstamp

    - name: Set variables
      set_fact:
        cur_date: "{{tstamp.stdout[0:10]}}"

    - name: Add vm custom attributes
      vmware_guest_custom_attributes:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        state: present
        validate_certs: no
        attributes:
          - name: DateCreation
            value: "{{cur_date}}"
      delegate_to: localhost
      register: attributes

# ajout d'une nic pout port group vlan-loubna
    - name: add a nic on network with vlan id 1000
      vmware_guest_network:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        datacenter: Datacenter
        validate_certs: no
        name: Deb-loubna
        networks:
          - name : VLAN-Loubna
            device_type : vmxnet3
            state: new
      delegate_to: localhost
#

    - name: Redimensionner le disque à 5G
      vmware_guest_disk:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        datacenter: Datacenter
        validate_certs: no
        name: Deb-loubna
        disk:
          - size_gb: 5
            autoselect_datastore: True
            unit_number: 0
            scsi_controller: 0
      delegate_to: localhost

    - name: Set the state of a virtual machine to poweron
      vmware_guest:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        validate_certs: no
        folder: /
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy

    - name: Get Tags from given VM Name
      block:
        - name: Get virtual machine info
          vmware_vm_info:
            hostname: vcsa.formation.lan
            username: loubna
            password: F0rmation!
            folder: /
            validate_certs: no
          delegate_to: localhost
          register: vm_info
          until: vm_info.instance.ipv4 is not none

        - debug:
            msg: "{{ item.tags }}"
          with_items:
            - "{{ vm_info.virtual_machines | json_query(query) }}"
          vars:
            query: "[?guest_name=='Deb-loubna']"
...
