---
- name: Configuration hyperviseur
  hosts: local

  tasks:

    - name: Add  VM Portgroup to Cluster
      vmware_portgroup:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        cluster_name: Cluster
        switch: vSwitch0
        portgroup: VLAN-Loubna
        vlan_id: 1000
        validate_certs: no
        state: present 
      delegate_to: localhost

    - name: Create a tag loubna
      vmware_tag:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        validate_certs: no
        category_id: 'urn:vmomi:InventoryServiceCategory:ae1957ef-839b-468c-ac6a-df722535aeb1:GLOBAL'
        tag_name: loubna
        tag_description: Tag loubna dans la catégorie Proprio
        state: present
      delegate_to: localhost


#    - name: Get category id from the given tag
#      vmware_tag_info:
#        hostname: vcsa.formation.lan
#        username: loubna
#        password: F0rmation!
#        validate_certs: no
#      register: tag_details
#    - debug:
#        msg: "{{ tag_details.tag_facts }}"

#Création de la vm loubna
    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        validate_certs: no
        name: Deb-loubna
        folder: /
        template: DebTemplate
        datacenter: Datacenter
      delegate_to: localhost

# Ajout de tag sur la machine loubna
    - name: Add tags to a virtual machine
      vmware_tag_manager:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        validate_certs: no
        tag_names:
          - loubna
        object_name: Deb-loubna
        object_type: VirtualMachine
        state: add
      delegate_to: localhost

## Modif de la date de création
    - name: Get timestamp from the system
      shell: "date +%d-%m-%Y%H-%M-%S"
      register: tstamp

    - name: Set variables
      set_fact:
        cur_date: "{{tstamp.stdout[0:10]}}"

    - name: Add vm custom attributes
      vmware_guest_custom_attributes:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        state: present
        validate_certs: no
        attributes:
          - name: DateCreation
            value: "{{cur_date}}"
      delegate_to: localhost
      register: attributes

#Mise à jour de la Compatibilité materiel 
    - name: Mise à jour de la Compatibilité materiel à la version 14
      vmware_guest:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        validate_certs: no
        hardware:
          version: 14
      delegate_to: localhost

# Mise à jour de l'OS à 10
    - name: Mise à jour de l'OS à 10
      vmware_guest:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        validate_certs: no
        guest_id: debian10_64Guest
      delegate_to: localhost

# ajout d'une nic pout port group vlan-loubna
    - name: add a nic on network with vlan id 1000
      vmware_guest_network:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        datacenter: Datacenter
        validate_certs: no
        name: Deb-loubna
        networks:
          - name : VLAN-Loubna
            device_type : vmxnet3
            state: new
      delegate_to: localhost

#Redimensionner le disque à 5G

    - name: Redimensionner le disque à 5G
      vmware_guest_disk:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        datacenter: Datacenter
        validate_certs: no
        name: Deb-loubna
        disk:
          - size_gb: 5
            autoselect_datastore: True
            unit_number: 0
            scsi_controller: 0
      delegate_to: localhost

    - name: Set the state of a virtual machine to poweron
      vmware_guest:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        validate_certs: no
        datacenter: Datacenter
        state: poweredon
        wait_for_ip_address : yes
      delegate_to: localhost
      #register: vm_result

    - name: Récupération de l'ip à partie des facts vm
      vmware_guest_info:
        hostname: vcsa.formation.lan
        username: loubna
        password: F0rmation!
        name: Deb-loubna
        datacenter: Datacenter
        validate_certs: no
      register: vm_facts
      delegate_to: localhost

    - name: fait pour ip
      set_fact:
        vm_ip: "{{ vm_facts.instance.ipv4 }}" 

 #   - name: debug
 #     debug:
 #       msg: "{{ vm_facts['instance']['ipv4'] }}"
  #    register: ipv4

    - name: Ajout de la vm debian à l'inventaire
      ansible.builtin.add_host:
        name: Debian
        ansible_host: "{{ vm_ip }}"
        ansible_user: dawan
        ansible_password: dawan

    - name: debug
      debug:
        var: vm_ip 

- name: Configuration vm debian
  hosts: Debian

  tasks:

    - name: deployer la clé publique pour user dawan
      ansible.posix.authorized_key:
        user: dawan
        key: "{{ lookup('file', '/home/loubna/.ssh/id_rsa.pub') }}"
...

